language: python

python:
  - "3.5"
  - "3.6"

# command(s) to install dependencies
install:
    - pip install -r requirements.txt -r test-requirements.txt
    - python setup.py develop

# command to run tests
script: 
    - pytest
